### ISSUE TITLE
some artifacts are missing

### ISSUE THREAD

**Issue by tonnyhideyori** [dbs-leipzig/gradoop_demo#13]
this dependence could not be resolved: org.opencypher:flink-cypher:jar:0.2.4-SNAPSHOT
when installing the demo with mvn clean install

**Comment by galpha** [comment]
Hi @tonnyhideyori thx for your issue! Yes, you are absolutely right. You can fix it by changing the variable `<dep.gradoop.version>0.5.1</dep.gradoop.version>` to `<dep.gradoop.version>0.6.0-SNAPAHOT</dep.gradoop.version>` in the `pom.xml`. We prepare a new stable gradoop release right now. As soon we are finished with that I'll update the gradoop version in the parent pom accordingly.

**Comment by tonnyhideyori** [comment]
the error still persist :
Could not resolve dependencies for project org.gradoop:gradoop-demo:jar:0.2.0: Failure to find org.gradoop:gradoop-flink:jar:0.6.0-SNAPAHOT in https://repo.maven.apache.org/maven2

**Comment by galpha** [comment]
Ups, there was a typo in the name of the updated version. Sry ^^ 
`<dep.gradoop.version>0.6.0-SNAPAHOT</dep.gradoop.version>` -> `<dep.gradoop.version>0.6.0-SNAPSHOT</dep.gradoop.version>`

**Comment by tonnyhideyori** [comment]
I real down know what is wrong still an error 
Failed to execute goal on project gradoop-demo: Could not resolve dependencies for project org.gradoop:gradoop-demo:jar:0.2.0: Could not find artifact org.gradoop:gradoop-flink:jar:0.6.0-SNAPSHOT
this is my propertis 
`<properties>
        <dep.flink.version>1.7.2</dep.flink.version>
        <dep.gradoop.version>0.6.0-SNAPSHOT</dep.gradoop.version>
        <dep.jersey.version>1.19.3</dep.jersey.version>
        <dep.gson.version>2.8.0</dep.gson.version>
        <dep.mongodb.version>3.3.0</dep.mongodb.version>
    </properties>`

**Comment by galpha** [comment]
Looks like maven does not know where to find the snapshot artifacts. Pls add the following to your `pom.xml`.
```
<repositories>
    <repository>
        <id>oss.sonatype.org-snapshot</id>
        <url>http://oss.sonatype.org/content/repositories/snapshots</url>
        <releases><enabled>false</enabled></releases>
        <snapshots><enabled>true</enabled></snapshots>
    </repository>
</repositories>
```
