### ISSUE TITLE
Unknown life cycle phase

### ISSUE THREAD

**Issue by tonnyhideyori** [dbs-leipzig/gradoop_demo#14]
I having problem to execute the demo the console bring this error:
Unknown lifecycle phase ".mainClass=org.gradoop.demo.server.Server". You must specify a valid lifecycle phase or a goal in the format `<plugin-prefix>:<goal> or <plugin-group-id>:<plugin-artifact-id>[:<plugin-version>]:<goal>`

**Comment by galpha** [comment]
Hey @tonnyhideyori thx for closing the other issue. 

So just for understanding. You successfully installed the gradoop_demo artifacts using `mvn clean install`. After that you tried to run `mvn exec:java -Dexec.mainClass="org.gradoop.demo.server.Server"` 

Correct?

**Comment by tonnyhideyori** [comment]
yes that was what i did but i got that error

**Comment by galpha** [comment]
Okay I see, sry for the delayed answer. What maven and java version do you use?

We are currently building gradoop and gradoop demo with maven2 and java 1.8.

**Comment by tonnyhideyori** [comment]
this is my maven verison: Apache Maven 3.6.3
java verison: Java version: 12.0.1

**Comment by galpha** [comment]
Okay, the maven version should be fine. Neither gradoop nor the gradoop-demo is compatible with java 12. You should try to install java 8 and try to execute the demo again.

**Comment by tonnyhideyori** [comment]
i checked again my java version is 1.8.0_221

**Comment by tonnyhideyori** [comment]
ok it works,it seems the problem was using a powershell to execute the command i tried with cmd prompt it works thanks, for your time

**Comment by xianjhuang** [comment]
> ok it works,it seems the problem was using a powershell to execute the command i tried with cmd prompt it works thanks, for your time

i got the same problem, just wanna know why powershell couldn't work

**Comment by Baba097** [comment]
> J'ai un problème pour exécuter la démo. La console affiche l'erreur suivante : Phase de cycle de vie inconnue « .mainClass=org.gradoop.demo.server.Server ». Vous devez spécifier une phase de cycle de vie valide ou un objectif au format suivant :`<plugin-prefix>:<goal> or <plugin-group-id>:<plugin-artifact-id>[:<plugin-version>]:<goal>`
